---
build_requires:
  DBD::SQLite: 1.14
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.52
  Test::Warn: 0.1
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-DBI
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Cache::Memcached: 0
  Cache::Simple::TimedExpiry: 0.21
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::ReturnValue: 0.4
  Class::Trigger: 0.12
  Clone: 0
  DBI: 0
  DBIx::DBSchema: 0.34
  Data::Page: 2.0
  DateTime: 0.34
  DateTime::Format::ISO8601: 0
  DateTime::Format::Strptime: 0
  Encode: 2.1
  Exporter::Lite: 0
  Hash::Merge: 0
  Lingua::EN::Inflect: 0
  Object::Declare: 0.22
  Scalar::Defer: 0.1
  Time::Duration: 0
  Time::Duration::Parse: 0.06
  UNIVERSAL::require: 0.11
  URI: 0
  YAML::Syck: 0
  perl: 5.8.3
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.64
