build_requires: 
  DBD::SQLite: 0
  Test::More: 0.52
distribution_type: module
generated_by: Module::Install version 0.640
license: perl
name: Jifty-DBI
no_index: 
  directory: 
    - ex
    - inc
    - t
requires: 
  Cache::Simple::TimedExpiry: 0.21
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::ReturnValue: 0.4
  Clone: 0
  DBI: 0
  DBIx::DBSchema: 0.29
  Data::Page: 0
  DateTime: 0.34
  DateTime::Format::ISO8601: 0
  DateTime::Format::Strptime: 0
  Encode: 2.1
  Exporter::Lite: 0
  Hash::Merge: 0
  Lingua::EN::Inflect: 0
  Object::Declare: 0.22
  Scalar::Defer: 0.1
  UNIVERSAL::require: 0
  YAML::Syck: 0
  perl: 5.8.3
  version: 0
version: 0.41
