name: Jifty-DBI
version: 0.08
license: perl
distribution_type: module
build_requires:
  Test::More: 0.52
  DBD::SQLite: 0
requires:
  perl: 5.8.3
  DBI: 0
  Encode: 2.1
  Exporter::Lite: 0
  UNIVERSAL::require: 0
  Lingua::EN::Inflect: 0
  Class::ReturnValue: 0.4
  Class::Accessor: 0
  Clone: 0
  Cache::Simple::TimedExpiry: 0.21
  Data::Page: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.46
