build_requires:
  DBD::SQLite: 0
  Test::More: 0.52
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: Jifty-DBI
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Cache::Simple::TimedExpiry: 0.21
  Class::Accessor: 0
  Class::ReturnValue: 0.4
  Class::Data::Inheritable: 0
  Class::Accessor: 0
  Clone: 0
  DBI: 0
  Data::Page: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
no_index:
  directory:
    - t
    - ex
    - inc
generated_by: Module::Install version 0.46
