name: Jifty-DBI
version: 0.02
license: perl
distribution_type: module
build_requires:
  Test::More: 0.52
requires:
  DBI: 0
  Want: 0
  Encode: 0
  UNIVERSAL::require: 0
  Class::ReturnValue: 0.4
  Cache::Simple::TimedExpiry: 0.21
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
