build_requires:
  DBD::SQLite: 0
  Test::More: 0.52
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: Jifty-DBI
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Cache::Simple::TimedExpiry: 0.21
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  Class::ReturnValue: 0.4
  Clone: 0
  DBI: 0
  DBIx::DBSchema: 0.28
  Data::Page: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  Encode: 2.1
  Exporter::Lite: 0
  Lingua::EN::Inflect: 0
  UNIVERSAL::require: 0
  perl: 5.8.3
version: 0.11
